### ISSUE TITLE
"Reveal Structure" causes add-in to fail for .xlsm file

### ISSUE THREAD

**Issue by bzorn** [plasma-umass/ExceLint-addin#12]
Some files with .xlsm extension cause Excelint to fail when Reveal Structure is used:
![image](https://user-images.githubusercontent.com/5445979/62087640-54e81a80-b217-11e9-93a3-a2e9db7baed4.png)

**Comment by emeryberger** [comment]
Fixed with https://github.com/plasma-umass/ExceLint-addin/commit/e40136efd87588832ae9865e36f492957d5a9c9c.

*Explanation*: ExceLint used to repeatedly use the range API to get formatting attributes to discount the likelihood of merging fixes that cross formatting regimes. For this sheet, this was extremely time consuming, and the desktop client treated it as a timeout.

This fix does two things to address this:
* First, it now generates the color map before computing the ranking, so there is a visible indication of progress. This is not the most important improvement, but it is nice to show something faster.
* Second, and more importantly, the code now uses the hot-off-the-press, just-released [getCellProperties](https://docs.microsoft.com/en-us/javascript/api/excel/excel.range?view=office-js#getcellproperties-cellpropertiesloadoptions-) API to get all formatting attributes en masse, and then processes it (without any further Excel API calls).

The result is _a lot_ more responsive. For example, for the sheet mentioned, on the Mac client, the entire ExceLint processing cycle used to take over 80 seconds. It now finishes in 5 seconds.
